name: Pull request

on: [pull_request]

jobs:

  build_and_push_Docker_image:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.event.pull_request.head.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build onsdigital/go-launch-a-survey Docker image
        run: docker build -t onsdigital/go-launch-a-survey:$TAG -f Dockerfile .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to onsdigital/go-launch-a-survey with $TAG
        run: docker push onsdigital/go-launch-a-survey:$TAG
